In [5]:
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [6]:
history = pd.read_csv('historyenv.csv')
med = pd.read_csv('evaluationmedical.csv')
survey = pd.read_csv('survey_vitals.csv')

In [7]:
history.head()

,objectId,numberofIndividualsLivingintheHouse,numberofChildrenLivinginHouseUndertheAgeof5,yearsLivedinthecommunity_1-2,yearsLivedinthecommunity_1_2,yearsLivedinthecommunity_3-4,yearsLivedinthecommunity_3_4,yearsLivedinthecommunity_5-10,yearsLivedinthecommunity_5_10,yearsLivedinthecommunity_lessThan1,...,wheretrashleftbetweenpickups_outside house,wheretrashleftbetweenpickups_sidewalk,wheretrashleftbetweenpickups_street,houseownership_owned,houseownership_rented,bathroomAccess_N,bathroomAccess_Y,stoveType_cementStove-Ventilation,stoveType_openfire-noVentilation,stoveType_stoveTop
0,Psto9poSCx,4,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,y6DJO1kLFl,4,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,sdPbSYrGCW,4,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
3,GiArohoFUo,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,rnNw8AxEix,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
survey.head()

,objectId,latitude,longitude,weight,pulse,bloodSugar,M,F,age,marriageStatus_concubine,...,province_Constanza,province_Consuelo,province_La Vega,province_None,province_San Pedro de Macoris,province_Santiago,insuranceProvider_ARS Humano,insuranceProvider_None,insuranceProvider_Other,insuranceProvider_Senasa
0,XHCkKebF4a,18.912087,-70.743801,NaN,NaN,NaN,0,1,34.0,0,...,0,0,0,1,0,0,0,1,0,0
1,nCqmOAp4r9,NaN,NaN,NaN,NaN,NaN,1,0,36.0,1,...,0,0,0,1,0,0,0,1,0,0
2,E6Muqo5331,NaN,NaN,NaN,NaN,NaN,0,1,41.0,1,...,0,0,0,1,0,0,0,1,0,0
3,LwMJ2wrMkZ,NaN,NaN,NaN,NaN,NaN,0,1,30.0,0,...,0,0,0,1,0,0,0,1,0,0
4,4kBFEjUSNz,NaN,NaN,NaN,NaN,NaN,0,1,49.0,0,...,0,0,0,1,0,0,0,1,0,0

In [10]:
med.head()

,objectId,AssessmentandEvaluation_No,AssessmentandEvaluation_Yes,planOfAction_cardiology,planOfAction_dermatology,planOfAction_gastroenterology,planOfAction_general medicine,planOfAction_general surgery,planOfAction_gynecology,planOfAction_laryngology,...,trauma_induced_gradually,trauma_induced_suddenly_but_not_due_to_trauma,trauma_induced_suddenly_due_to_trauma,condition_progression_constant,condition_progression_improve,condition_progression_worsen,AssessmentandEvaluation_Surgical_No,AssessmentandEvaluation_Surgical_Yes,immediate_follow_up_No,immediate_follow_up_Yes
0,bWCqNwtKYL,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,056xDPGU2U,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,FoatG2gGXl,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,dzkEclDkh9,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ao66iABlET,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
m = 0
h = 0
for o in survey.objectId:
    in_med = False
    in_history = False
    for om in med.objectId:
        if om == o:
            in_med = True
    for oh in history.objectId:
        if oh == o:
            in_history = True
    if not in_med:
        m+=1
    if not in_history:
        h+=1
        
print("M: " + str(m))
print("H: " + str(h))

M: 5564
H: 4245

In [19]:
history.size

618772

In [22]:
med.size

458955

In [23]:
t=0 
for om in med.objectId:
    in_history = False
    for oh in history.objectId:
        if oh == om:
            in_history = True
    if not in_history:
        t+=1
print(t)

3182